#!/bin/bash

rm -rf /var/jb/usr/bin/Filza

if [ -f /var/jb/Library/LaunchDaemons/com.tigisoftware.filza.webdavserver.plist ]
then
	launchctl unload /var/jb/Library/LaunchDaemons/com.tigisoftware.filza.webdavserver.plist
	rm -rf /var/jb/Library/LaunchDaemons/com.tigisoftware.filza.webdavserver.plist
fi

