#!/bin/bash

if [ -e /var/jb/Applications/Filza.app ]
then
	chown -R root:admin /var/jb/Applications/Filza.app
fi

chown root /var/jb/usr/libexec/filza/FilzaHelper
chown root /var/jb/Library/LaunchDaemons/com.tigisoftware.filza.helper.plist
launchctl load -w /var/jb/Library/LaunchDaemons/com.tigisoftware.filza.helper.plist

chown root /var/jb/usr/libexec/filza/Filza
chmod ug+s /var/jb/usr/libexec/filza/Filza
rm -rf /var/jb/usr/bin/Filza
ln -s var/jb/usr/libexec/filza/Filza /usr/bin/Filza

if [ -d /var/mobile/Library/Filza/.Trash ]
then
	chown mobile:mobile /var/mobile/Library/Filza/.Trash
fi

if [ -d /var/mobile/Library/Filza/.Trash.metadata ]
then
	chown mobile:mobile /var/mobile/Library/Filza/.Trash.metadata
fi

rm -rf /var/mobile/Library/Caches/ImageTables
if [ -f /var/root/Library/Filza/extensions.plist ]
then
	rm -rf /var/mobile/Library/Filza/extensions.plist
        mv /var/root/Library/Filza/extensions.plist /var/mobile/Library/Filza/extensions.plist
	chown -R mobile:mobile /var/mobile/Library/Filza/extensions.plist
fi

if [ -f /var/root/Library/Filza/links.plist ]
then
        rm -rf /var/mobile/Library/Filza/links.plist
        mv /var/root/Library/Filza/links.plist /var/mobile/Library/Filza/links.plist
        chown -R mobile:mobile /var/mobile/Library/Filza/links.plist
fi

if [ -f /var/root/Library/Filza/filza.db ]
then
        rm -rf /var/mobile/Library/Filza/filza.db
        mv /var/root/Library/Filza/filza.db /var/mobile/Library/Filza/filza.db
        chown -R mobile:mobile /var/mobile/Library/Filza/filza.db
fi

if [ -f /var/root/Library/Preferences/com.tigisoftware.Filza.plist ]
then
	rm -rf /var/mobile/Library/Preferences/com.tigisoftware.Filza.plist
        mv /var/root/Library/Preferences/com.tigisoftware.Filza.plist /var/mobile/Library/Preferences/com.tigisoftware.Filza.plist
        chown -R mobile:mobile /var/mobile/Library/Preferences/com.tigisoftware.Filza.plist
fi

if [ -e /var/jb/usr/bin/Filza ]
then
	/var/jb/usr/bin/Filza mobile uicache &> /dev/null
fi
